# Generated by Django 2.0.3 on 2018-04-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Forum', 'verbose_name_plural': 'Forums'},
        ),
    ]
